// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmGijG7o76ZYWuc6IgGxkl2oH4IAerb5Y',
    appId: '1:63775372251:web:2c3f22c87c4d3a95beedfe',
    messagingSenderId: '63775372251',
    projectId: 'gen-lang-client-0267232601',
    authDomain: 'gen-lang-client-0267232601.firebaseapp.com',
    storageBucket: 'gen-lang-client-0267232601.appspot.com',
    measurementId: 'G-TN59DH31G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1PsDA4BiFJ1kVZUtRNR2lvG5oiIOiwYI',
    appId: '1:63775372251:android:80cc86dfe072b5ddbeedfe',
    messagingSenderId: '63775372251',
    projectId: 'gen-lang-client-0267232601',
    storageBucket: 'gen-lang-client-0267232601.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnGB6V5bNmywUemtmJkNUXPT3LWvvIfvg',
    appId: '1:63775372251:ios:1b3a8442ad399bacbeedfe',
    messagingSenderId: '63775372251',
    projectId: 'gen-lang-client-0267232601',
    storageBucket: 'gen-lang-client-0267232601.appspot.com',
    iosClientId: '63775372251-91odh0b48jkrdagbi8q9669tbuld6fmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappKd',
  );
}
